### ISSUE TITLE
[BUG] Mac users not able to generate file using ng generate ng-ag-grid-schematics:nags

### ISSUE THREAD

**Issue by lakviat** [Sgryts/ng-ag-grid-schematics#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1419" alt="image" src="https://github.com/s-gryt/ng-ag-grid-schematics/assets/29146176/6d225822-903d-4a57-9cef-b29e6737a04f">

### Expected Behavior

File generation failure 

### Steps To Reproduce

1 - npm install ng-ag-grid-schematics
2 - ng add ng-ag-grid-schematics
3 - ng generate ng-ag-grid-schematics:nags
   * Provide Name
   * Provide Path
   * Provide Project

4 - Styling and State Management
   * Choose Style
   * State management 
   
Error :
   
   Fro more info follow instructions provided in the README
   https://www.npmjs.com/package/ng-ag-grid-schematics?activeTab=readme

**Comment by s-gryt** [comment]
I've identified a documentation flaw and an uncaught exception in cases where the project name is not specified. Your feedback is highly valuable, and I've taken the necessary steps to address these issues. The following commits have been merged to implement the fixes:

b1b8032742d97f11f32af107e181e929bcf7128f
e61d200c6b8a69ff02f4185ef2b9aeee821d0016
8cee95e8555dc65d540b05423daba589ad714fcd

Furthermore, it's worth noting that the schematics are designed to be operating system-agnostic, ensuring compatibility across different platforms. You can confidently run them anywhere without concerns.

I've also added screenshots with inputs for the prompt and highlighted where to locate the project name information. This should provide clearer guidance for users.

Thank you for bringing this to my attention, and please feel free to reach out if you have any additional feedback or concerns.

![Screenshot from 2023-12-12 21-48-10](https://github.com/s-gryt/ng-ag-grid-schematics/assets/28329870/12f6f883-ec3b-472d-9a0b-c6724560b1c2)
![Screenshot from 2023-12-12 22-08-59](https://github.com/s-gryt/ng-ag-grid-schematics/assets/28329870/d3f04681-a6b9-4938-a77c-030702b9b028)
